FROM ubuntu:latest
LABEL authors="kauan"

FROM golang:latest AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o app .

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/app .

# Receber variáveis como argumentos (do GitHub Actions)
ARG SERVER_CONN_STR
ARG MONGO_URI
ARG MONGO_INITDB_ROOT_USERNAME
ARG MONGO_INITDB_ROOT_PASSWORD
ARG MONGO_PORT
ARG ME_CONFIG_MONGODB_ADMINUSERNAME
ARG ME_CONFIG_MONGODB_ADMINPASSWORD
ARG ME_CONFIG_MONGODB_SERVER
ARG ME_PORT
ARG JAEGER_PORT
ARG JAEGER_PORT_TCP
ARG JAEGER_UI_PORT
ARG JAEGER_HTTP_PORT
ARG PROMETHEUS_PORT
ARG JAEGER_ENDPOINT
ARG WORKFLOW_NAME
ARG OTELCOLLECTOR_CONN_STR

# Exportar como variáveis de ambiente
ENV SERVER_CONN_STR=$SERVER_CONN_STR \
    MONGO_URI=$MONGO_URI \
    MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME \
    MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD \
    MONGO_PORT=$MONGO_PORT \
    ME_CONFIG_MONGODB_ADMINUSERNAME=$ME_CONFIG_MONGODB_ADMINUSERNAME \
    ME_CONFIG_MONGODB_ADMINPASSWORD=$ME_CONFIG_MONGODB_ADMINPASSWORD \
    ME_CONFIG_MONGODB_SERVER=$ME_CONFIG_MONGODB_SERVER \
    ME_PORT=$ME_PORT \
    JAEGER_PORT=$JAEGER_PORT \
    JAEGER_PORT_TCP=$JAEGER_PORT_TCP \
    JAEGER_UI_PORT=$JAEGER_UI_PORT \
    JAEGER_HTTP_PORT=$JAEGER_HTTP_PORT \
    PROMETHEUS_PORT=$PROMETHEUS_PORT \
    JAEGER_ENDPOINT=$JAEGER_ENDPOINT \
    WORKFLOW_NAME=$WORKFLOW_NAME \
    OTELCOLLECTOR_CONN_STR=$OTELCOLLECTOR_CONN_STR

EXPOSE 8080 27017 8081 16686 14268 9090 4317

CMD ["./app"]
