services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - ${ME_PORT}:${ME_PORT}
    env_file:
      - .env
    depends_on:
      - mongo

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4317:4317"
    depends_on:
      - jaeger
      - prometheus
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - ${JAEGER_PORT}:${JAEGER_PORT_TCP} # TCP port for Jaeger agent
      - ${JAEGER_UI_PORT}:${JAEGER_UI_PORT} # Web UI
      - ${JAEGER_HTTP_PORT}:${JAEGER_HTTP_PORT} # HTTP port for spans
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./configs/prometheus/setup.yml:/etc/prometheus/prometheus.yml
    ports:
      - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}

volumes:
  mongo_data:
